#!/usr/bin/env python3
"""Import Fallen Forest source assets from the owner's canonical Drive archives.

The workflow downloads the two outer ZIP files. This script only performs local,
deterministic extraction and intentionally excludes the forbidden Amazing Grace clip.
"""
from __future__ import annotations

import argparse
import io
import shutil
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / "assets"

PRIMARY_PACKS = {
    "grass.zip": "environment/grass",
    "first-person-arms.zip": "player/arms",
    "flashlight.zip": "player/flashlight",
    "document-file-folder-1.zip": "props/documents",
    "pickup-truck.zip": "vehicles/pickup",
    "toe-locust-by-doumty.zip": "characters/locust",
    "the-boiled-one-horror-game-boiled-one.zip": "characters/boiled_one",
    "Видео для скримера вареного.zip": "video/boiled_one",
}

APPROVED_SCREAMERS = {
    "jakes-screamer.mp3",
    "the-screamer-shared-between-mallie-and-jenny.mp3",
}


def safe_extract_zip(zf: zipfile.ZipFile, destination: Path) -> None:
    destination.mkdir(parents=True, exist_ok=True)
    dest_resolved = destination.resolve()
    for info in zf.infolist():
        if info.is_dir():
            continue
        target = (destination / info.filename).resolve()
        if dest_resolved not in target.parents and target != dest_resolved:
            raise RuntimeError(f"Unsafe ZIP path: {info.filename}")
        target.parent.mkdir(parents=True, exist_ok=True)
        with zf.open(info) as src, target.open("wb") as dst:
            shutil.copyfileobj(src, dst)


def extract_nested(outer: zipfile.ZipFile, nested_name: str, destination: Path) -> None:
    data = outer.read(nested_name)
    with zipfile.ZipFile(io.BytesIO(data)) as nested:
        safe_extract_zip(nested, destination)


def import_primary(path: Path) -> None:
    with zipfile.ZipFile(path) as outer:
        for archive_name, relative_destination in PRIMARY_PACKS.items():
            print(f"Importing {archive_name} -> assets/{relative_destination}")
            extract_nested(outer, archive_name, ASSETS / relative_destination)

        screamers = outer.read("скримеры.zip")
        destination = ASSETS / "audio" / "screamers"
        destination.mkdir(parents=True, exist_ok=True)
        with zipfile.ZipFile(io.BytesIO(screamers)) as nested:
            for info in nested.infolist():
                if info.is_dir():
                    continue
                name = Path(info.filename).name
                if name not in APPROVED_SCREAMERS:
                    print(f"Skipping non-canonical screamer: {name}")
                    continue
                (destination / name).write_bytes(nested.read(info))


def import_trees(path: Path) -> None:
    with zipfile.ZipFile(path) as outer:
        # Black spruce: the real model/LOD payload is itself nested in source/*.zip.
        spruce_outer_data = outer.read("realistic-hd-black-spruce-1038.zip")
        with zipfile.ZipFile(io.BytesIO(spruce_outer_data)) as spruce_outer:
            source_data = spruce_outer.read("source/Picea mariana HD_Arctic mat 100.zip")
            with zipfile.ZipFile(io.BytesIO(source_data)) as source_zip:
                safe_extract_zip(source_zip, ASSETS / "environment" / "trees" / "black_spruce")

        # Dead fir pack: import its OBJ/MTL and matching textures from the nested source ZIP.
        dead_outer_data = outer.read("4-dead-firs-trees-pack-high-poly (1).zip")
        with zipfile.ZipFile(io.BytesIO(dead_outer_data)) as dead_outer:
            source_data = dead_outer.read("source/firs.zip")
            with zipfile.ZipFile(io.BytesIO(source_data)) as source_zip:
                safe_extract_zip(source_zip, ASSETS / "environment" / "trees" / "dead_firs")

        # Preserve the low-poly pack payload and exposed textures. Its source model is packaged
        # as RAR, so keeping the original source archive avoids destructive conversion here.
        low_outer_data = outer.read("low-poly-forest-tree-pack.zip")
        with zipfile.ZipFile(io.BytesIO(low_outer_data)) as low_outer:
            safe_extract_zip(low_outer, ASSETS / "environment" / "trees" / "low_poly_pack")


def write_manifest() -> None:
    model_exts = {".fbx", ".glb", ".gltf", ".obj"}
    models = sorted(p.relative_to(ROOT).as_posix() for p in ASSETS.rglob("*") if p.suffix.lower() in model_exts)
    text = [
        "# Imported asset inventory",
        "",
        "Generated by `tools/import_drive_assets.py` from the project owner's canonical Google Drive archives.",
        "",
        "## 3D model files",
        "",
    ]
    text.extend(f"- `{model}`" for model in models)
    text.extend([
        "",
        "## Canonical audio rule",
        "",
        "Only the two approved Locust screamers are imported. `amazing-grace-analog-horror.mp3` is intentionally excluded.",
        "",
        "## Provenance",
        "",
        "Drive is the source of truth for these user-provided project files. Do not silently replace them with unrelated Internet assets.",
        "",
    ])
    (ROOT / "docs" / "ASSET_INVENTORY.md").write_text("\n".join(text), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--all", required=True, type=Path, help="Path to 'все нужное.zip'")
    parser.add_argument("--trees", required=True, type=Path, help="Path to 'Деревья.zip'")
    args = parser.parse_args()

    import_primary(args.all)
    import_trees(args.trees)
    write_manifest()
    print("Fallen Forest Drive asset import complete.")


if __name__ == "__main__":
    main()
