extends SceneTree

const TARGETS := [
	"res://assets/characters/locust/source/T_O_E Locust - By Doumty.fbx",
	"res://assets/characters/boiled_one/source/BoiledOne.fbx",
	"res://assets/player/arms/source/fpsarms.fbx",
	"res://assets/player/flashlight/source/flashlightfbx.fbx",
	"res://assets/props/documents/source/document_file_folder (1).glb",
	"res://assets/environment/grass/source/Grass.fbx",
	"res://assets/environment/trees/black_spruce/Picea mariana HD_Arctic mat 100_LOD0.fbx",
	"res://assets/environment/trees/black_spruce/zzz_LODs/LOD2/Picea mariana HD_Arctic mat 100_LOD2.fbx",
	"res://assets/environment/trees/dead_firs/firs.obj",
	"res://assets/environment/trees/low_poly_pack/source/Tree_Pack.fbx",
	"res://assets/vehicles/pickup/source/Pickup Afghanistan.fbx",
]

var lines: PackedStringArray = []

func _initialize() -> void:
	lines.append("# Godot imported asset report")
	lines.append("")
	lines.append("Generated by Godot itself after importing the canonical Drive assets.")
	lines.append("")
	for path: String in TARGETS:
		inspect_scene(path)
	var file := FileAccess.open("res://docs/ASSET_IMPORT_REPORT.md", FileAccess.WRITE)
	if file == null:
		push_error("Unable to create ASSET_IMPORT_REPORT.md")
		quit(2)
		return
	file.store_string("\n".join(lines) + "\n")
	file.close()
	quit(0)

func inspect_scene(path: String) -> void:
	lines.append("## `%s`" % path.trim_prefix("res://"))
	lines.append("")
	if not ResourceLoader.exists(path):
		lines.append("**IMPORT FAILED / RESOURCE NOT FOUND**")
		lines.append("")
		return
	var resource: Resource = load(path)
	if not resource is PackedScene:
		lines.append("Imported resource type: `%s` (not PackedScene)" % resource.get_class())
		lines.append("")
		return
	var root: Node = (resource as PackedScene).instantiate()
	if root == null:
		lines.append("**PACKED SCENE COULD NOT INSTANTIATE**")
		lines.append("")
		return

	lines.append("Root: `%s` (`%s`)" % [root.name, root.get_class()])
	var stats := {
		"meshes": 0,
		"skeletons": 0,
		"animations": 0,
		"mesh_min": Vector3(INF, INF, INF),
		"mesh_max": Vector3(-INF, -INF, -INF),
	}
	walk(root, stats, 0, Transform3D.IDENTITY, path)
	lines.append("")
	lines.append("Summary: meshes=%d, skeletons=%d, animations=%d" % [stats.meshes, stats.skeletons, stats.animations])
	if int(stats.meshes) > 0:
		var min_v: Vector3 = stats.mesh_min
		var max_v: Vector3 = stats.mesh_max
		var size: Vector3 = max_v - min_v
		lines.append("Combined mesh AABB size (import units): `(%.4f, %.4f, %.4f)`" % [size.x, size.y, size.z])
		lines.append("Combined mesh Y range: `%.4f .. %.4f`" % [min_v.y, max_v.y])
	lines.append("")
	root.free()

func _tree_pack_classification(path: String, node_name: String) -> String:
	if "low_poly_pack" not in path:
		return ""
	var n := node_name.to_lower()
	for excluded: String in ["grass", "bush", "shrub", "rock", "ground", "fern", "plant"]:
		if excluded in n:
			return " [EXCLUDE:%s]" % excluded
	if "tree" in n or "trunk" in n or "branch" in n:
		return " [TREE-CANDIDATE]"
	return " [REVIEW]"

func walk(node: Node, stats: Dictionary, depth: int, parent_transform: Transform3D, source_path: String) -> void:
	var indent := "  ".repeat(depth)
	var current_transform: Transform3D = parent_transform
	if node is Node3D:
		current_transform = parent_transform * (node as Node3D).transform

	if node is MeshInstance3D:
		var mesh_node := node as MeshInstance3D
		stats.meshes = int(stats.meshes) + 1
		var aabb: AABB = mesh_node.get_aabb()
		var corners: Array[Vector3] = [
			aabb.position,
			aabb.position + Vector3(aabb.size.x, 0, 0),
			aabb.position + Vector3(0, aabb.size.y, 0),
			aabb.position + Vector3(0, 0, aabb.size.z),
			aabb.position + Vector3(aabb.size.x, aabb.size.y, 0),
			aabb.position + Vector3(aabb.size.x, 0, aabb.size.z),
			aabb.position + Vector3(0, aabb.size.y, aabb.size.z),
			aabb.position + aabb.size,
		]
		for corner: Vector3 in corners:
			var p: Vector3 = current_transform * corner
			var min_v: Vector3 = stats.mesh_min
			var max_v: Vector3 = stats.mesh_max
			stats.mesh_min = Vector3(minf(min_v.x, p.x), minf(min_v.y, p.y), minf(min_v.z, p.z))
			stats.mesh_max = Vector3(maxf(max_v.x, p.x), maxf(max_v.y, p.y), maxf(max_v.z, p.z))
		var classification := _tree_pack_classification(source_path, str(node.name))
		lines.append("%s- Mesh `%s`: AABB `(%.3f, %.3f, %.3f)`%s" % [indent, node.name, aabb.size.x, aabb.size.y, aabb.size.z, classification])
	elif node is Skeleton3D:
		var skeleton := node as Skeleton3D
		stats.skeletons = int(stats.skeletons) + 1
		lines.append("%s- Skeleton `%s`: %d bones" % [indent, node.name, skeleton.get_bone_count()])
	elif node is AnimationPlayer:
		var player := node as AnimationPlayer
		var libraries: Array[StringName] = player.get_animation_library_list()
		var names: PackedStringArray = []
		for library_name: StringName in libraries:
			var library: AnimationLibrary = player.get_animation_library(library_name)
			for animation_name: StringName in library.get_animation_list():
				names.append((str(library_name) + "/" if str(library_name) != "" else "") + str(animation_name))
		stats.animations = int(stats.animations) + names.size()
		lines.append("%s- AnimationPlayer `%s`: %s" % [indent, node.name, ", ".join(names) if not names.is_empty() else "no animations"])

	for child: Node in node.get_children():
		walk(child, stats, depth + 1, current_transform, source_path)
