extends SceneTree

const TARGETS := [
	"res://assets/characters/locust/source/T_O_E Locust - By Doumty.fbx",
	"res://assets/characters/boiled_one/source/BoiledOne.fbx",
	"res://assets/player/arms/source/fpsarms.fbx",
	"res://assets/player/flashlight/source/flashlightfbx.fbx",
	"res://assets/props/documents/source/document_file_folder (1).glb",
	"res://assets/environment/grass/source/Grass.fbx",
	"res://assets/environment/trees/black_spruce/Picea mariana HD_Arctic mat 100_LOD0.fbx",
	"res://assets/environment/trees/black_spruce/zzz_LODs/LOD2/Picea mariana HD_Arctic mat 100_LOD2.fbx",
	"res://assets/vehicles/pickup/source/Pickup Afghanistan.fbx",
]

var lines: PackedStringArray = []

func _initialize() -> void:
	lines.append("# Godot imported asset report")
	lines.append("")
	lines.append("Generated by Godot itself after importing the canonical Drive assets.")
	lines.append("")
	for path in TARGETS:
		inspect_scene(path)
	var file := FileAccess.open("res://docs/ASSET_IMPORT_REPORT.md", FileAccess.WRITE)
	if file == null:
		push_error("Unable to create ASSET_IMPORT_REPORT.md")
		quit(2)
		return
	file.store_string("\n".join(lines) + "\n")
	file.close()
	quit(0)

func inspect_scene(path: String) -> void:
	lines.append("## `%s`" % path.trim_prefix("res://"))
	lines.append("")
	if not ResourceLoader.exists(path):
		lines.append("**IMPORT FAILED / RESOURCE NOT FOUND**")
		lines.append("")
		return
	var resource := load(path)
	if not resource is PackedScene:
		lines.append("Imported resource type: `%s` (not PackedScene)" % resource.get_class())
		lines.append("")
		return
	var root := (resource as PackedScene).instantiate()
	if root == null:
		lines.append("**PACKED SCENE COULD NOT INSTANTIATE**")
		lines.append("")
		return

	lines.append("Root: `%s` (`%s`)" % [root.name, root.get_class()])
	var stats := {
		"meshes": 0,
		"skeletons": 0,
		"animations": 0,
		"mesh_min": Vector3(INF, INF, INF),
		"mesh_max": Vector3(-INF, -INF, -INF),
	}
	walk(root, root, stats, 0)
	lines.append("")
	lines.append("Summary: meshes=%d, skeletons=%d, animations=%d" % [stats.meshes, stats.skeletons, stats.animations])
	if stats.meshes > 0:
		var min_v: Vector3 = stats.mesh_min
		var max_v: Vector3 = stats.mesh_max
		var size := max_v - min_v
		lines.append("Combined mesh AABB size (import units): `(%.4f, %.4f, %.4f)`" % [size.x, size.y, size.z])
		lines.append("Combined mesh Y range: `%.4f .. %.4f`" % [min_v.y, max_v.y])
	lines.append("")
	root.free()

func walk(root: Node, node: Node, stats: Dictionary, depth: int) -> void:
	var indent := "  ".repeat(depth)
	if node is MeshInstance3D:
		var mesh_node := node as MeshInstance3D
		stats.meshes += 1
		var aabb := mesh_node.get_aabb()
		var local_to_root := root.global_transform.affine_inverse() * mesh_node.global_transform if root is Node3D else Transform3D.IDENTITY
		var corners := [
			aabb.position,
			aabb.position + Vector3(aabb.size.x, 0, 0),
			aabb.position + Vector3(0, aabb.size.y, 0),
			aabb.position + Vector3(0, 0, aabb.size.z),
			aabb.position + Vector3(aabb.size.x, aabb.size.y, 0),
			aabb.position + Vector3(aabb.size.x, 0, aabb.size.z),
			aabb.position + Vector3(0, aabb.size.y, aabb.size.z),
			aabb.position + aabb.size,
		]
		for corner in corners:
			var p := local_to_root * corner
			stats.mesh_min = Vector3(minf(stats.mesh_min.x, p.x), minf(stats.mesh_min.y, p.y), minf(stats.mesh_min.z, p.z))
			stats.mesh_max = Vector3(maxf(stats.mesh_max.x, p.x), maxf(stats.mesh_max.y, p.y), maxf(stats.mesh_max.z, p.z))
		lines.append("%s- Mesh `%s`: AABB `(%.3f, %.3f, %.3f)`" % [indent, node.name, aabb.size.x, aabb.size.y, aabb.size.z])
	elif node is Skeleton3D:
		var skeleton := node as Skeleton3D
		stats.skeletons += 1
		lines.append("%s- Skeleton `%s`: %d bones" % [indent, node.name, skeleton.get_bone_count()])
	elif node is AnimationPlayer:
		var player := node as AnimationPlayer
		var libraries := player.get_animation_library_list()
		var names: PackedStringArray = []
		for library_name in libraries:
			var library := player.get_animation_library(library_name)
			for animation_name in library.get_animation_list():
				names.append((str(library_name) + "/" if str(library_name) != "" else "") + str(animation_name))
		stats.animations += names.size()
		lines.append("%s- AnimationPlayer `%s`: %s" % [indent, node.name, ", ".join(names) if not names.is_empty() else "no animations"])

	for child in node.get_children():
		walk(root, child, stats, depth + 1)
